### ISSUE TITLE
deploy radiant extension in shiny server

### ISSUE THREAD

**Issue by kmezhoud** [radiant-rstats/radiant.design#1]
Dear Dr Vencent,
I installed radiant from minicran (it seems not necessary) and in cloned `radiant.desing` in cloud shiny [server](http://46.101.227.144:3838/radiant.design/).
In previous version of radiant there were double server.R , ui.R, global.R files.
In this version we have to POINT shiny-server to the `inst/app/` directory.
How to?
Thanks

**Comment by kmezhoud** [comment]
If I browse to `/inst/app`  the app works.

**Comment by vnijs** [comment]
If you just want to run radiant.design on a server you need to install radiant.data (minicran has the latest version) and clone radiant.design. I'll close this since it seems to got the "point-to" part.
