### ISSUE TITLE
Sampling Random Number Key Error

### ISSUE THREAD

**Issue by brichard1638** [radiant-rstats/radiant.design#3]
In the sampling function, the list object element item called "seldat" returns random numbers that are rounded up from 9 digits to 7. The numbers are correct, they are just truncated through rounding This is a problem if you wanted to aggregate the data back to a larger data set of original samples using the randomly assigned numbers as a key. You would have to initiate additional code to offset the difference in the truncated numbers assigned to the sample size.

It is believed that the random numbers assigned in seldat should match, with precision, the same 9 digits provided in the random numbers that are stored in the list item "rnd_number."

I emailed the output highlighting an example consistent with this issue.

**Comment by vnijs** [comment]
Could this perhaps be a formatting issue rather than rounding? If I set `options(digits=20)` I don't see any evidence of rounding in the below. 

![image](https://user-images.githubusercontent.com/2998956/103590710-6705c800-4ea3-11eb-926b-dd27a8fd99d5.png)

Also, could you expand on the below? 

"This is a problem if you wanted to aggregate the data back to a larger data set of original samples using the randomly assigned numbers as a key."

Why would you use the randomly assigned numbers as keys? Why not some other key that is part of your data? I may be missing something in your application area so the more detail you can provide the better.

**Comment by brichard1638** [comment]
Vincent:::

You are focused on the wrong part of the list object. Look at the comparison between rnd_number and seldat. I am specifically referencing the relationship between these two list items.

In other words, compare the numbers between rnd_number and the rnd_number in seldat.

That is what I believe serves as the error.

You would use the random numbers as keys if you wanted to develop a data process model that reproduced the production of the sample. You might, for example, work with a team that requires a reproducible method for the use of sampling. In that case, how else would you show the random method for sampling? I would argue that the best way to do that would be to show the relationship between the random numbers as keys and the samples BEYOND what is in seldat. Seldat provides the output but it provides no information on how that data was connected outside of the sample.

That's how I would think about it. I can tell you that there is a drive in the world of data science to be able to reproduce any kind of results that are being generated using tools like R or Python.

For example, if I were to just provide you with 20 random samples from a data set of 200 line items without anything other than the 20 random samples, how would you know that those were randomly chosen? How would you be able to confirm with certainty that there was a data process model driving the sample selection?

Perhaps my approach is an unorthodox one. However, when I examine and assess an R package I am looking for the highest degree of flexibility and utility of functionality. Your sampling function meets the criteria and is extraordinary in form but only if the sampling results by way of the random numbers assigned precisely match the random numbers initially generated for the entire data set.

I hope this makes sense and is clear. Your sampling function is great but that bug prohibits maximum utility in being able to connect those random number keys back to the original data set. For example, you may want to add data by way of additional columns to qualify the data sample.

In that case, the current incarnation of the sampling function makes it much more difficult to do that. I also believe it reduces the credibility of the sample since you are assigning random numbers in one part of the list that do not precisely match the random numbers assigned in the seldat list which contains the randomly selected samples.

Please advise if this explanation is still ambiguous in terms of context.

Warm regards,

Brice Richard
Data Scientist
Washington, DC



________________________________

**Comment by vnijs** [comment]
Reproducibility is essential, I agree. Using a float as a key of some kind seems really odd to me however. The R shiny packages has a function `shiny:::createUniqueId` to create a unique sequence of letters and integers. Now that I could see as a key. There are even platforms that do not support "longdoubles" so how would you even match without allowing some kind of tolerance.

RE your point "In other words, compare the numbers between rnd_number and the rnd_number in seldat." As far as I can see these are the same numbers, only the printing format that R uses is different. If you have option(digits = 10) and I have options(digits = 20) these thing would look different.

RE your point "I were to just provide you with 20 random samples from a data set of 200 line items without anything other than the 20 random samples, how would you know that those were randomly chosen?" Interesting theoretical point but I don't how that would ever happen in practice. 

Perhaps I could see your point of view better if you created a minimal reproducible example with R code. Perhaps one using just R and one with Radiant that highlights the issue you are concerned about.

**Comment by brichard1638** [comment]
Vincent::::

Ultimately it sounds like you don't see a value proposition in making the changes I've proposed. That's fine. I am privileged that you took the time to consider a discussion with me on the idea.

Assuming that the proposed changes I've offered will not be made, I will make a note of this issue and will provide the appropriate workaround.

Thanks again for the contribution you and your team have made with the radiant.design package.

I am still a fan of this R package.

Warm regards,

Brice Richard
Data Scientist
Washington, DC
________________________________

**Comment by vnijs** [comment]
Thanks. I'll close for now. If you can provide a clear reproducible example of a bug I'm happy to take another look
